export { Logo } from './Logo'
export { Header } from './Header'
export { Footer } from './Footer'
export { Banner } from './Banner'
export { TabsContent } from './Tabs'
export { SocialMedia} from './SocialMedia'